### ISSUE TITLE
Looking For Maintainer

### ISSUE THREAD

**Issue by spwhitt** [nix-community/nix-zsh-completions#44] opened 2023-01-28 21:23 UTC
It has been many years since I've been actively using Nix, and as a result I am no longer in a position to maintain this project. I have been fortunate that contributors like @hedning and @olejorgenb have stepped in to fill the void in the intervening years. I am very thankful to them for that.

Is anyone interested in adopting maintainership of this project? I don't believe there is a lot to do, but if you are at least using Nix regularly you're in a better position than I.

I've also been considering if it would make sense to transfer this project to nix-community. Is this a reasonable option? @Mic92

**Comment by SebTM** [comment] 2023-01-30 01:25
+1 for transferring to nix-community (even I can not decide/speak for them) - I would try to review/test/merge contributions or fix easy bugs but not that deep into Nix :)

**Comment by spwhitt** [comment] 2023-01-30 01:51
Your help is certainly welcome! Fortunately deep Nix knowledge isn't required in this repo

**Comment by spwhitt** [comment] 2023-01-30 02:00
Closed by accident. I transfered the repo nix-community earlier today which hopefully will help. I'll leave this open for now in order to make it clear that help is wanted and appreciated.

**Comment by spwhitt** [comment] 2023-01-30 02:03
Closed by accident. I'll leave this open for now to make it clear that help is wanted, even though the transfer to nix-community may by itself help. Thanks all!

**Comment by 0pointerexception** [comment] 2023-02-05 20:51
I just read on discourse that this project needs a new maintainer. I do have experience in writing and testing zsh completions (as I do this at work quite regularly), know the CLI tooling of nix somewhat well, so I’d like to offer my help maintaining this project or at least contribute to it every once in a while.

**Comment by spwhitt** [comment] 2023-02-08 16:12
Thanks for volunteering! With the transfer to nix-community I don't think I can manage contributor access to the repository anymore. If it were up to me I'd give both of you access and check back in a few months to make sure there's not a flaming pile of rubble here :rofl:. It's no matter though because in my opinion you don't need access to get started. I bet @Mic92 will give perms to whomever seems to be doing the job. Any thoughts on this, Jörg?

**Comment by Mic92** [comment] 2023-02-09 08:53
@spwhitt I made a team that can edit this repository with you as the maintainer and you can freely add more people to whomever is in the nix-community org.

**Comment by Mic92** [comment] 2023-02-09 08:54
https://github.com/orgs/nix-community/teams/nix-zsh-completions/discussions

**Comment by SebTM** [comment] 2023-02-09 23:07
@Mic92 How can I become a member of nix-community?

**Comment by Mic92** [comment] 2023-02-10 15:42
@SebTM sent you an invite.

**Comment by SebTM** [comment] 2023-02-11 12:51
> @SebTM sent you an invite.

@Mic92 Thanks you :)

**Comment by 0pointerexception** [comment] 2023-02-11 21:25
@Mic92 I'm not a part of the nix-community org on here yet, if you'd find a minute to spare, I'd like to ask for an invite as well.

**Comment by Mic92** [comment] 2024-03-16 20:51
@theesm sended you an invite as well.

**Closed by Mic92** 2024-03-16 20:51 UTC

**Comment by SebTM** [comment] 2025-12-14 13:46
I'm not using nix as much as I have in the past, so I would appreciate support on this 🙏🏻

**Comment by hi5ato** [comment] 2025-12-21 07:11
As I'm new to Nix, I'm not sure how community maintenance works.
Enabling zsh via Home Manager provides far superior completion features to those offered by this repository.
Even if you install zsh's Nixpkgs outside of Home Manager, the zsh package should include completion scripts.
Does this mean that maintenance of this repository is unnecessary?

**Comment by SebTM** [comment] 2025-12-23 22:58
Hey, a quick check as I wasn't sure myself about the current state shows me that this module is installed when you enable the zsh-module via home-manager:

https://github.com/nix-community/home-manager/blob/master/modules/programs/zsh/default.nix#L450

This combined with still incoming issue reports/pull-requests let me believe it's still accurate to look for further maintenance.

**Comment by hi5ato** [comment] 2025-12-24 03:12
My misunderstanding that HM was superior
was due to the influence of

https://github.com/NixOS/nix/raw/refs/heads/master/misc/zsh/completion.zsh.


So, this repo's code also needs maintenance for the old syntax nix cmmand.

**Comment by KushalLukhi** [comment] 2026-03-24 02:14
Hi maintainers — I'm Kushal (@KushalLukhi). I'd like to volunteer as a maintainer/contributor for this project.

I can help with:
- issue triage and reproduction
- reviewing/fixing open bugs
- dependency/security updates
- release/support chores

Happy to start with PR-based contributions and earn trust progressively. If you're open, please share the preferred onboarding path and first tasks.

**Comment by SebTM** [comment] 2026-03-26 21:25
Hey @KushalLukhi, thanks for the offer to support - I don't use as much nix atm. why I can't spend so much as in the past so any help is appreciated.

From a quick look I couldn't find Nix/Nixpkgs or related contributions maybe you can let us know about your current knowledge-state and experience to look for a first task?
