### ISSUE TITLE
Flakes completion

### ISSUE THREAD

**Issue by Kloenk** [nix-community/nix-zsh-completions#32] opened 2020-06-09 09:13 UTC
### Description
Completion with nix flakes support.

The new nix flakes branch also includes an own bash completions function backed by the nix command, and also has some power output, which I did not see yet in the non flakes nix.

### Reproduction steps
- Install the newest nix flakes version (self compiled from `github:nixos/nix/flakes` in my case).
- type `nix build`
- press tab

- got an output saying:
~~~
_arguments:comparguments:325: invalid argument: (--option ^[[3mNAME^[[0m ^[[3mVALUE^[[0m)^[[3mNAME^[[0m[set a Nix configuration option (overriding nix.conf)]
~~~

### System

- nix-zsh-completions version: installed via nixpkgs/master (commit: `2f79f25963e77677c6d29614a7022dc1d4fb39db`, it exists on the path `2qgipp21a711bj73wacvipp10y4apgnn-nix-zsh-completions-0.4.4`)
- ZSH version: 5.8
- NIX_PATH: irrelevant, using nix flakes (and only contains `/etc/src`)

 - system: `"x86_64-linux"`
 - host os: `Linux 5.6.16, NixOS, 20.09.20200608.2f79f25 (Nightingale)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20200606_087a3e3`
 - nixpkgs: `/etc/src/nixpkgs`

**Comment by Ma27** [comment] 2020-07-21 22:38
@Kloenk the problem is that positional args are displayed using the ANSI escape string `\x1b[3m` now rather than `<` in `nix --help`. The error itself can be fixed by replacing `<` with `$'\e\[3m'` and `>` with `$'\e\[0m'`.

However, there are a few more regressions after that. Also, we'd have to support `#`-based completions to query the flake registry.

I'm currently hacking on a patch. As soon as it's somehow usable, I'll publish a draft-PR.

**Comment by Ma27** [comment] 2020-07-26 00:28
@Kloenk @shrb would you like to test the current state of #34 in case you have time/resources for this? While it's far from ready, it's in a rather usable state (I'm currently using it by default on my machine to thoroughly test it).

**Comment by srhb** [comment] 2020-07-26 01:00
Absolutely, I'll check it out tomorrow.

**Comment by regnat** [comment] 2020-09-17 12:16
For the `nix` command you could probably use the new `NIX_GET_COMPLETIONS` magic (see https://github.com/NixOS/nix/blob/master/misc/bash/completion.sh for how it's used for bash and https://github.com/NixOS/nix/blob/b721877b85bbf9f78fd2221d8eb540373ee1e889/src/libutil/args.cc for the actual logic). I guess that would be more reliable and require less maintenance than parsing the `--help` pages.

It's strictly less expressive atm because it only gets you the possible completions without describing them, but that would be a reasonably easy addition

**Comment by Ma27** [comment] 2020-09-18 12:34
I'm not sure if I'm misunderstanding this but I never got this to retrieve useful output (i.e. flags, attrs etc.).

**Comment by regnat** [comment] 2020-09-18 15:35
> I'm not sure if I'm misunderstanding this but I never got this to retrieve useful output (i.e. flags, attrs etc.).

I don't have enough zsh-fu to write a custom completer out of this, but the idea is that you can dynamically ask Nix to tell you the possible completions. For example:

```console
# Get the options for `nix build` that start with `--no`
$ NIX_GET_COMPLETIONS=2 nix build --no
no-filenames
--no-link
--no-net
--no-registries
--no-update-lock-file
--no-write-lock-file
# Get the possible attrs completion in the `nixpkgs` flake
$ NIX_GET_COMPLETIONS=2 nix build nixpkgs#zsh
filenames
nixpkgs#zsh
nixpkgs#zsh-autoenv
nixpkgs#zsh-autosuggestions
nixpkgs#zsh-bd
nixpkgs#zsh-command-time
nixpkgs#zsh-completions
nixpkgs#zsh-fast-syntax-highlighting
nixpkgs#zsh-git-prompt
nixpkgs#zsh-history
nixpkgs#zsh-history-substring-search
nixpkgs#zsh-navigation-tools
nixpkgs#zsh-nix-shell
nixpkgs#zsh-powerlevel10k
nixpkgs#zsh-powerlevel9k
nixpkgs#zsh-prezto
nixpkgs#zsh-syntax-highlighting
nixpkgs#zsh-you-should-use
```

The first line of the output tells whether you should add a filename-based completion, and the rest is a list of possible completions.
It could certainly be extended to print a description alongside the completion where it makes sense

**Comment by clhodapp** [comment] 2020-10-08 04:02
Eventually, I may work on a PR to properly integrate this into the repo, but for now a workaround seems to be putting this in your zshrc:

```
function _nix() {
  local ifs_bk="$IFS"
  input=("${(Q)words[@]}")
  IFS=$'\n'
  local res=($(NIX_GET_COMPLETIONS=$((CURRENT - 1)) "$input[@]"))
  IFS="$ifs_bk"
  tpe="$res[1]"
  suggestions=(${res:1})
  if [[ "$tpe" == filenames ]]; then
    compadd -fa suggestions
  else
    compadd -a suggestions
  fi
}

compdef _nix nix
```

**Comment by clhodapp** [comment] 2020-10-08 04:07
Oh dang, in minimizing it, I made some sort of change that undid something I previously had working: completing nix attributes after hashes in flake URLs. Once I fix it, I'll repost.

**Comment by clhodapp** [comment] 2020-10-08 04:08
False alarm! It still works!

**Comment by Ma27** [comment] 2020-10-08 13:49
That's fine as well. If that's the better working solution, we can close #34 after that.

**Comment by clhodapp** [comment] 2020-10-08 18:30
Oooh sorry, @Ma27, I misjudged how far along your PR was. It seems to me like there are multiple reasonable routes here:

Your approach is much more "zsh-native" and can potentially give much richer completions at the cost of being fiddlier and requiring more maintenance work as Nix changes.

My approach is much simpler, since most of the logic to generate the completions is inside of `nix` itself. The big drawback is that the completions will pretty much just be a simple text list, since the `nix` feature was motivated by bash and that's all that bash supports.

I suppose there _could_ be an outside chance that nix itself could someday be enhanced for zsh with support for richer built-in completions that leverage e.g. the help strings that already live in the codebase (but that's totally not my department!).

**Comment by Ma27** [comment] 2020-10-08 21:30
> I suppose there could be an outside chance that nix itself could someday be enhanced for zsh with support for richer built-in completions that leverage e.g. the help strings that already live in the codebase (but that's totally not my department!).

I asked Eelco on IRC before filing this PR and he said that this is not planned, for now at least, so I wouldn't bet on that :) 

> My approach is much simpler, since most of the logic to generate the completions is inside of nix itself.

I fully agree.

As you state that this is mostly designed for bash, have you checked if it's actually suitable for zsh's completion facility (in terms of usage and completeness)? So I'd love to see things like getting flake-names and attrs completed like we all know it from ZSH. If that's the case, I *think* that I'd prefer your approach then.

**Comment by clhodapp** [comment] 2020-10-09 00:26
It seems to be fairly complete and I would assume that any deficiency would be improved on the `nix` side over time.

Here is an example for completing flake names:
```
~/nix $ nix build 'flake:'
flake:blender-bin            flake:hydra                  flake:nixops                 flake:nixpkgs                flake:patchelf
flake:ch-nix                 flake:nimble                 flake:nixos-hardware         flake:nixpkgs/release-19.09  flake:templates
flake:dwarffs                flake:nix                    flake:nixos-homepage         flake:nur                    
```

And one for flake attributes:
```
~/nix $ nix build 'ch-nix#'
ch-nix#checks                     ch-nix#homeManagerModule          ch-nix#nix-user-bash-launcher     ch-nix#packages
ch-nix#home-manager               ch-nix#nixosConfigurations        ch-nix#nix-user-zsh-launcher      
ch-nix#homeManagerConfigurations  ch-nix#nixosModule                ch-nix#overlay                    
```

The big drawback is going to be that there is no help text at all (showing the raw output this time so it's clear what it looks like):
```
~/nix $ NIX_GET_COMPLETIONS=1 nix b
no-filenames
build
bundle
```

You'd have to build that yourself by somehow cross-referencing the suggestions with the help text.

**Comment by regnat** [comment] 2020-10-09 07:50
Wow thanks a lot @clhodapp , that's awesome :fireworks: 

> I asked Eelco on IRC before filing this PR and he said that this is not planned, for now at least, so I wouldn't bet on that :)

I actually went ahead before seeing that yesterday and implemented it on the Nix side https://github.com/NixOS/nix/pull/4128.
That looks like a small-enough change, I'd be surprised if there was any major issue with it

**Comment by Ma27** [comment] 2023-03-27 08:55
Latest Nix versions actually have a built-in zsh completion, does your `fpath` point to `share/zsh-site-functions` of `/run/current-system` (or where your Nix is installed into)?

**Comment by peterbecich** [comment] 2023-09-09 06:18
Possibly relevant:
https://github.com/nix-community/home-manager/issues/2562

**Comment by peterbecich** [comment] 2023-09-09 06:33
More about that: 
https://github.com/NixOS/nix/pull/5308/files#diff-0e411d402c0ff04a84100545fac3cc3cc2bd43f09703836d1f3da140940c5dd9R215-R217

According to this comment it works with Flakes:
https://github.com/NixOS/nix/pull/4871

**Comment by ghostbuster91** [comment] 2023-09-10 15:48
fyi: In my case removing `targets.genericLinux.enable = true;` from home-manager configuration fixed the issue of not having completion for the `nix` command. I know that I shouldn't have `targets.genericLinux.enable` set for nixos but it was just a leftover from the earlier non-nixos times that I haven't notice before.

**Comment by SebTM** [comment] 2024-03-17 13:23
Hey, it looks like this is resolved - anyone against closing it? (will revisit in a week if not)

**Comment by SebTM** [comment] 2024-03-24 16:09
As suggested going ahead and close it as already resolved - please open a new issue if you encounter issue again 🙏

**Closed by SebTM** 2024-03-24 16:09 UTC
